### ISSUE TITLE
Player Friction bug

### ISSUE THREAD

**Issue by NAT0P0TAT0** [thommoboy/There-are-no-brakes#11]
Players need to be made 'frictionless' to stop them from sticking to walls and ceilings
(and player movement modified to fit that so they don't slide around)

**Comment by BlackFuse** [comment]
No idea how to do it _(:з)∠)_
Is anyone can give an idea?

**Comment by NAT0P0TAT0** [comment]
ok so friction in unity is handled by 'physics materials', when you make physmaterials you can set how 'bouncy' they are and how much friction they have, basically you just make a physmaterial that has friction set to 0 and apply that to the players.

The player movement script would need to be updated to set horizontal speed to 0 if the player isn't pressing either direction (since they're frictionless they'll slide around otherwise), unless of course they're being carried or thrown.
