### ISSUE TITLE
FIX CAMERA

### ISSUE THREAD

**Issue by NAT0P0TAT0** [thommoboy/There-are-no-brakes#110]

**Comment by dataGuyJosh** [comment]
HUD currently hides industrial tutorial door at top right
HUD hides red/green indicators in industrial maze level

**Comment by NAT0P0TAT0** [comment]
in tutorial, seems to zoom in too much when theyre close together and not enough when theyre further apart

**Comment by NAT0P0TAT0** [comment]
sometimes zooms in too far in when players are close together

**Comment by NAT0P0TAT0** [comment]
set camera to use the 'zoom out' position if it tries to go further back/away than that position

**Comment by dataGuyJosh** [comment]
Camera zooms too far right in adventurer level (possibly fixed but unsure)
