### ISSUE TITLE
PRE TESTING - Player walk and idle animation doesnt loop correctly

### ISSUE THREAD

**Issue by NAT0P0TAT0** [thommoboy/There-are-no-brakes#12]
also jittering when player stops walking

**Comment by NAT0P0TAT0** [comment]
turns out the jittering when stopping walking was because part of the movement script was using input axis while another was using get keydown so there was a tiny window where they didnt match and the player would freak out, should be fixed now.

walk animation still doesnt loop though

**Comment by thommoboy** [comment]
Fixed as of today
