### ISSUE TITLE
Bottom right pressure plate can get "stuck" in the on position

### ISSUE THREAD

**Issue by dataGuyJosh** [thommoboy/There-are-no-brakes#147]
it appears to have something to do with interacting with the weight object but I'm not sure exactly what triggers it.

**Comment by NAT0P0TAT0** [comment]
have not been able to replicate

**Comment by dataGuyJosh** [comment]
From memory I haven't seen this bug in quite a while so I've lowered its priority

**Comment by NAT0P0TAT0** [comment]
can always re-open it if it happens again
