### ISSUE TITLE
HUD explanation

### ISSUE THREAD

**Issue by dataGuyJosh** [thommoboy/There-are-no-brakes#149]
Tutorial should explain this to the player, I might end up making a diagram to show on the back wall but seriously needs to be explained considering it's a major component of the puzzles

**Comment by NAT0P0TAT0** [comment]
wasnt it supposed to be in the cutscene? but yeah theres a textbox for it but people just run past it

**Comment by dataGuyJosh** [comment]
Ideally the cutscene does explain it and we can close this issue yea

**Comment by NAT0P0TAT0** [comment]
removed Cloud part of HUD, should be simpler now

**Comment by dataGuyJosh** [comment]
no longer going in cutscene due to running out of time, we'll make an explanation of it in the tutorial, maybe highlight it in a popup or something

**Comment by NAT0P0TAT0** [comment]
hid HUD in tutorial and added HUD info as a post-it in level 1
