### ISSUE TITLE
Industrial_HorizontalSlider.cs vs IN_VerticalSlider.cs

### ISSUE THREAD

**Issue by dataGuyJosh** [thommoboy/There-are-no-brakes#15]
horizontal slider breaks the naming/sorting convention of the other scripts and should be moved, (minor issue but I don't want to break anything by renaming/moving it myself

**Comment by NAT0P0TAT0** [comment]
i just had it named different because the horizontal one is not 'interactive' at all, its just an environmental thing specific to that scene, so i wasnt sure about the name/location

**Comment by BlackFuse** [comment]
Done. Create an empty horizontal axes.
