### ISSUE TITLE
Character visibility

### ISSUE THREAD

**Issue by dataGuyJosh** [thommoboy/There-are-no-brakes#150]
Quite a few people find it difficult to tell which character is which, the identify button is useful but more needs to be done
Some Possibilities:
Make indicators show by default when camera auto locks zoom
Make indicators more meaningful (e.g. Adventurer indicator "ADV" or a whip symbol, industrial "IND" or a lantern, Ancients "ANC" or an egyptian symbol --> Eye of Horus?)

**Comment by NAT0P0TAT0** [comment]
icons display automatically when the camera auto caps zoom
a highlighted background appears behind the player when icons appear
