### ISSUE TITLE
Crate in Pyramid Level

### ISSUE THREAD

**Issue by dataGuyJosh** [thommoboy/There-are-no-brakes#154]
If a player jumps and drops it in mid air (more common than you'd think!) it can be dropped into a position impossible for either player to reach due to the horizontal movement in the script for going up the pyramid.

Possible solution:
whenever the weight touches a platform move it to the origin (and up in the y axis) of the platform so it's always in line with a player, be especially careful with this at corners

If a player tries taking it through a door it usually becomes impossible to pick up again

Possible solution:
make it teleport to a nearby platform if a player tries to takes it too close to a door? not the best solution

**Comment by NAT0P0TAT0** [comment]
crate respawns if players try to take it to lower platforms, not sure about dropping it while in mid air tho
