### ISSUE TITLE
improvements to camera zoom

### ISSUE THREAD

**Issue by NAT0P0TAT0** [thommoboy/There-are-no-brakes#16]
First off I think a delay on zooming back in would help, players could tap it a couple times rather than having to hold it in (unless they want to keep it on permanently)
eg if i were somehow able to tap the zoom out button for only 1 frame, the camera would stay zoomed out for 1 frame and X seconds.

Secondly it would be a good idea to have the zoom out ability as a public function so it could be activated by scripts in the level (eg you just pulled a lever, lets see what that does)

**Comment by BlackFuse** [comment]
Done. Tried to only frozen vertical(x-axis) distance, so camera can move but can't zoom. But result is not good. Finally choose completely frozen the camera.

Can be closed if no other proposal.

**Comment by NAT0P0TAT0** [comment]
id say increase the time delay (maybe double it) and set the camera to keep zooming out to the normal distance as long as the time delay hasn't been triggered yet  (so basically if i tapped zoom out really quickly it wouldn't just zoom out a tiny bit, it would go all the way)
