### ISSUE TITLE
Audio Source/Listeners create different intensity in elevator sound effects when elevator rises

### ISSUE THREAD

**Issue by dataGuyJosh** [thommoboy/There-are-no-brakes#166]
Possible Solution:
All audio sources could be generated in run time with a paired audio listener (so that the distance never effects sound intensity)?

**Comment by NAT0P0TAT0** [comment]
or just put the audio listener on the audio manager (and get all the sounds to run through the audio manager)

**Comment by NAT0P0TAT0** [comment]
have moved audio sources and audio listener to the same object so movement and distance should no longer be an issue
