### ISSUE TITLE
Players complain about too much standing around waiting for others

### ISSUE THREAD

**Issue by dataGuyJosh** [thommoboy/There-are-no-brakes#169]
this is especially prominent in the pyramid level and to a small degree the industrial level

a possible solution is to add some minor additions to the levels to make them more busy

**Comment by NAT0P0TAT0** [comment]
it'll be difficult to remove this completely, especially with the industrial level since the players can end up in any number of positions before realizing exactly what they need to do

**Comment by NAT0P0TAT0** [comment]
have updated level designs, should help
