### ISSUE TITLE
PRE TESTING - Camera multitarget cutting players off screen

### ISSUE THREAD

**Issue by NAT0P0TAT0** [thommoboy/There-are-no-brakes#17]
looks fine when theyre close together, but if one player moves over to the right side the camera seems to center on them, even to the point of cutting the other players off the screen, instead of centering between the players.

(though maybe thats just cus im viewing it in editor?)

**Comment by BlackFuse** [comment]
Well, I think it is fine, or players cannot see the next section.

**Comment by NAT0P0TAT0** [comment]
if a player is on the left end and a player is on the right end you only get to see the right half of the level

**Comment by NAT0P0TAT0** [comment]
gets REALLY annoying when 2/3 characters go off the bottom of the screen

**Comment by NAT0P0TAT0** [comment]
moved the camera in Tutorial, Industrial and Adventurer levels, looks  better, will need a bit more testing to see how much players go off the screen edge
