### ISSUE TITLE
Tutorial text is often outright ignored, partially due to any one player moving

### ISSUE THREAD

**Issue by dataGuyJosh** [thommoboy/There-are-no-brakes#170]
more visuals should be used with less reliance on text boxes, having text boxes to explain some points is good but having many in the same level (even though we have the priority system) seems to make it very hard for players to understand some aspects e.g. the HUD or their ability

**Comment by NAT0P0TAT0** [comment]
have added post-it-notes to tutorial level, should make controls a lot more obvious
