### ISSUE TITLE
update the generic 'interact' popup

### ISSUE THREAD

**Issue by NAT0P0TAT0** [thommoboy/There-are-no-brakes#18]
At the moment its literally just some white text somewhere around the center of the screen, its not positioned great, and since there's no background it can be hard to see.

It should be replaced with something better looking, the updated version can just be applied to all the interactive objects that have an onGUI function.

**Comment by BlackFuse** [comment]
Improved. Fixed the bug that will display more than one popup box when players in different text trigger. See detail at IN_TextTrigger_ConetentControl.cs and IN_TextTrigger.cs.

**Comment by NAT0P0TAT0** [comment]
that's great, but that's a totally different issue, this issue is about the "Press Interact to use" popup that's used by winches/levers/lantern/pyramid-door

**Comment by NAT0P0TAT0** [comment]
actually ill just fix this now by linking them all to that text manager script you made

**Comment by NAT0P0TAT0** [comment]
done, could still be improved but a lot more visible than it used to be
