### ISSUE TITLE
Tutorial Ancient Door Bug

### ISSUE THREAD

**Issue by dataGuyJosh** [thommoboy/There-are-no-brakes#180]
The tutorial Ancient Door appears to be bugged in the current build, activating it will take you to the right position, but show the character phasing through the wall, trying to use the door to go BACK, to the left, will perform a similar bug but more importantly the player will go right instead, then fly around a bit and end up basically where they started. My description is awful so just test it by trying to use the door with the ancient character in the tutorial

**Comment by BlackFuse** [comment]
I'm  revive!!
Working on it just now

**Comment by BlackFuse** [comment]
Looks fixed
