### ISSUE TITLE
Make an installer

### ISSUE THREAD

**Issue by dataGuyJosh** [thommoboy/There-are-no-brakes#182]
This is the first of a series of Issues I'll make that basically just help people remember the criteria for the publishing phase. I may just end up pasting lecture dot points in some cases

Installer
- Easy and smooth process --> nice to have: installs and plays perfectly for **non-admin** users
- some file hosts don't take exe/msi files --> try to use a host that allows them --> can hide an exe/msi in a zip file
- helpful page links --> http://en.wikipedia.org/wiki/Windows_Installer
- **We will download and test on the S515 machines with a fresh Win7 install; it should be flawless there**

**Comment by NAT0P0TAT0** [comment]
have gotten a way to make a pretty decent installer, gotten my system to the point where I can just select a build and put in some basic info and it'll make the installer in a couple mins.
