### ISSUE TITLE
Menu updates

### ISSUE THREAD

**Issue by NAT0P0TAT0** [thommoboy/There-are-no-brakes#20]
text needs to sit on its actual box, not under them
credits page needs to be 'openable'
right-clicking auto starts game for some reason
might just be cus i'm in editor but i cant change the volume options

I don't think we need 'new game' / 'load game' options, game should just start

control options would be nice but not necessary. (also would probably have to be set up by pierce to work with the XBOX controller input stuff)

**Comment by BlackFuse** [comment]
what? I remember did some update on July!!
OK looks I lost them.. Will try restore/redo them with your recommendation~~
