### ISSUE TITLE
CREDITS PAGE

### ISSUE THREAD

**Issue by NAT0P0TAT0** [thommoboy/There-are-no-brakes#204]

**Comment by thommoboy** [comment]
Working on this as we speak

**Comment by thommoboy** [comment]
Found Images at:
Hieroglyphs:
1. https://flic.kr/p/auZz7h
Scarab: 
2. http://www.freepik.com/index.php?goto=74&idfoto=811080&term=scarab

**Comment by thommoboy** [comment]
https://www.freesound.org/

**Comment by BlackFuse** [comment]
Credits text will show as center mode, we don't need ":"
