### ISSUE TITLE
controller input in menus

### ISSUE THREAD

**Issue by NAT0P0TAT0** [thommoboy/There-are-no-brakes#29]
all game controls (move, jump, interact, zoom, restart, pause) to be accessible with controller inputs, game doesn't need to exclusively select one or the other, just accept either, then we could have 1 player on keyboard and 2 on controllers or any other combination, would also allow for switching from 1 to the other mid-game instantly with no problems or messing with settings.

(would also probably mean less code, eg instead of: if (controllers) codecodecode else codecodecode its just: if (up or A) jump)

**Comment by NAT0P0TAT0** [comment]
set it to work in tandem with keyboard, updated all the interactive object scripts to accept controller input

(still need controller input for menu usage/pause/zoom/restart)

**Comment by NAT0P0TAT0** [comment]
id say just reuse A and B for menu forward/back

**Comment by NAT0P0TAT0** [comment]
on most levels any of the the individual controller inputs for zoomout will zoomout the camera, but for pyramid level their zoomout button will only zoomout the camera thats looking at them

**Comment by NAT0P0TAT0** [comment]
ok i added controller input for pausing, zooming out and resetting the level, could still use menu control

**Comment by BlackFuse** [comment]
Don't delete axis input of "vertical" and "horizontal"~~ or volume slider in option panel will be disabled.

**Comment by NAT0P0TAT0** [comment]
playtesters accidentally paused the game at one point and were trying to get out for a while before someone just grabbed the mouse and clicked out, I think we can add this back to the to-do list

**Comment by dataGuyJosh** [comment]
Agreed, on a minor side note the tutorial popups should probably be dismissable via controllers as well

**Comment by NAT0P0TAT0** [comment]
they've been set back to not pausing anymore, were giving them the controls before the room starts and then just using the text boxes as reminders/extra detail

**Comment by BlackFuse** [comment]
Done it.
