### ISSUE TITLE
Some textboxes need to puase game and be bigger

### ISSUE THREAD

**Issue by NAT0P0TAT0** [thommoboy/There-are-no-brakes#41]
players sometimes missed messages or did see initial ones but didnt notice when the message had changed

basically set up a boolean on the text popup script and if the text popup function is called with the boolean as true the text box is bigger, the font is 2-3 times bigger and the timescale is stopped until they press a certain button

**Comment by BlackFuse** [comment]
Write 2 public function in test content controller script, please use Display()  or cancelDisplay() in future.
function you mentioned(enlarge and pause) is in it now.
No any test yet.

**Comment by BlackFuse** [comment]
More: same message only pause and enlarger 1 time.(should be, still no text)
