### ISSUE TITLE
Pyramid doors animated

### ISSUE THREAD

**Issue by NAT0P0TAT0** [thommoboy/There-are-no-brakes#5]
alter doors to animate rather than instantly teleporting player

**Comment by BlackFuse** [comment]
Finished.

**Comment by NAT0P0TAT0** [comment]
maybe instead of both doors opening and staying open until the player walks all the way through (and letting the player see that its literally just a corridor) the doors could open and close 1 at a time?

Like player uses door A, door A opens, player walks through doorway, door A closes, player keeps walking, door B opens, player walks through doorway, door B closes.
