### ISSUE TITLE
Need some indication that you can interact other than text box

### ISSUE THREAD

**Issue by NAT0P0TAT0** [thommoboy/There-are-no-brakes#55]
players didnt notice it sometimes, other times it got in the way of helpful popups they were actually trying to read

maybe give the object a bright outline when player is in range or something?

not only is more obvious but also allows player to see they can interact with something while there's another tutorial text popup, something that doesn't work now

**Comment by BlackFuse** [comment]
Have no idea, game scene will be mass if each text trigger has indication ...or just give a bright outline to Interactive objects when player closing to them?

**Comment by NAT0P0TAT0** [comment]
was saying interactive objects have bright outline when player in range instead of using a textbox

**Comment by NAT0P0TAT0** [comment]
have added basic outlining on trigger for the interactive objects, doesn't look amazing but it works, can re-open this issue if it pops up in playtesting more
