### ISSUE TITLE
Adventure level: Swing bug

### ISSUE THREAD

**Issue by BlackFuse** [thommoboy/There-are-no-brakes#61]
player get huge force to up and fly~~~~
Don't know what cause it.

**Comment by NAT0P0TAT0** [comment]
also hard to let go since the thing will disengage and re-engage instantly, needs a timeout

**Comment by NAT0P0TAT0** [comment]
re-engaging fixed but being pushed up still happens

**Comment by NAT0P0TAT0** [comment]
got it, swinging itself is a little slowed down but at least now you don't get rocketed towards the pole
