### ISSUE TITLE
Textures for the red/blue objects in Adventurer level

### ISSUE THREAD

**Issue by dataGuyJosh** [thommoboy/There-are-no-brakes#8]
HUD & Breakable Wall

**Comment by NAT0P0TAT0** [comment]
also anything else thats just red or blue

(and i fixed the pink thing in HUD, though since this is the second time its popped up it may happen again)

**Comment by NAT0P0TAT0** [comment]
also a cannon model for the dropping weight

**Comment by NAT0P0TAT0** [comment]
gave them some better looking materials as placeholder
