### ISSUE TITLE
NEED SOUND WORKING

### ISSUE THREAD

**Issue by dataGuyJosh** [thommoboy/There-are-no-brakes#9]
STUFF TO GET:
Game finished music (entire game complete, not level complete)

CURRENTLY IMPLEMENTED:
Train ambience
Menu music
Level music
Menu sounds
Level complete sound
game over sound
winch winding
Heavy object (stone?) being dragged (for cross)
Heavy object fall/thud (for sarcophagus)
Motor/Hydraulics running (for industrial moving platforms)
Lever being switched
Pressureplate being pressed/released

(EDIT THIS POST WHEN STUFF IS ADDED/UPDATED)

**Comment by NAT0P0TAT0** [comment]
Yeah the lack of sound was clearly noticed by playtesters, re-opening

**Comment by NAT0P0TAT0** [comment]
pretty sure the lack of footstep sound is actually a case of the sound constantly restarting rather than being allowed to loop, if you pause the game while walking the sound starts playing and loops until you resume

**Comment by NAT0P0TAT0** [comment]
ok yeah the audio manager was just playing the sound every frame without checking if it was already playing or not, that bug should be fixed now

but we still need some more sounds

**Comment by NAT0P0TAT0** [comment]
SOUND EFFECTS:
Level complete sound
game over sound
Landing after fall/jump (can probably use one of the unused footstep sounds)
Lever being switched
Pressureplate being pressed/released
Heavy object fall/thud (for sarcophagus)
Heavy object (stone?) being dragged (for cross)
Motor/Hydraulics running (for industrial moving platforms)

**Comment by BlackFuse** [comment]
Found a lots of sound effect, going to add some later

**Comment by BlackFuse** [comment]
Added Level complete, menu/pause button switch and game over sound, going to write a new sound script rather than just use public to call audio

**Comment by NAT0P0TAT0** [comment]
im just gonna implement sounds without the audio manager for the time being, we can set them up to use it later if necessary

**Comment by NAT0P0TAT0** [comment]
once the audio manager can play multiple sounds at the same time a bunch of scripts will need to be edited to use the audio manager instead of their own audio source

**Comment by NAT0P0TAT0** [comment]
have implemented the 'into - main loop - urgent loop' system
