### ISSUE TITLE
Main menu, confirm button(A/delta) need be pressed many times to work

### ISSUE THREAD

**Issue by BlackFuse** [thommoboy/There-are-no-brakes#91]
No idea why it is! Left click is no problem but on controller is terrible

**Comment by dataGuyJosh** [comment]
controller inputs allow players to enter the settings in the main menu but not the start of the game, needs fixing for the desk crit on thursday

**Comment by NAT0P0TAT0** [comment]
for me i can use a controller to open options or credits easy but the start game button doesn't work

**Comment by BlackFuse** [comment]
fixed!
