### ISSUE TITLE
player can use pulley by their HEAD

### ISSUE THREAD

**Issue by BlackFuse** [thommoboy/There-are-no-brakes#92]
May move the trigger higher?

Edit: Happened when one player on it and an other player use it as head

Edit 2: Players can jump to let the pulley up, that's not we want

**Comment by NAT0P0TAT0** [comment]
"Edit 2: Players can jump to let the pulley up, that's not we want"

Um thats absolutely what we want?  when you jump youre not weighing it down anymore, and many players instinctively jump to move it up, so we know its what people expect

**Comment by dataGuyJosh** [comment]
The players can activate the trigger for the second part of the adventurer puzzle (pulley system) from beneath the platform
