### ISSUE TITLE
Hint Arrow in tutorial section stays on until scene is changed (not reproducible for some reason)

### ISSUE THREAD

**Issue by BlackFuse** [thommoboy/There-are-no-brakes#93]
May move arrows depend on position of exit and cemera?

**Comment by NAT0P0TAT0** [comment]
wtf? the hint arrow was only added to tutorial level, and its disabled by the group door that leads to the adventurer section so it only appears in the ancient section
did someone copy the hint arrow into the other levels?

**Comment by dataGuyJosh** [comment]
what feng means is that in the first testing session today, we had a bug where the green right pointing arrow would stay on for the entire level once triggered, i've got the video footage but not sure why it happened, didn't happen in 2nd session, will show you at the meeting tonight
