### ISSUE TITLE
Wheel of train is not spinning

### ISSUE THREAD

**Issue by BlackFuse** [thommoboy/There-are-no-brakes#94]
=.=Don't know how to take part module, help

**Comment by dataGuyJosh** [comment]
Could you go into more detail? I'm not sure what you mean here sorry. Are you talking about the axles on the pulley system?

**Comment by NAT0P0TAT0** [comment]
the wheels of the train carriage?

**Comment by BlackFuse** [comment]
Ops sorry guys just saw this issue, I mean the wheel of train in Pyramid Level need spin

**Comment by NAT0P0TAT0** [comment]
this cant be done as the wheels are not separate objects, the 'wheel' objects have two wheels and a connector, so rotating it wouldn't spin the wheels, it would make them move around.

the only way to do this would be to make a new model for the train wheels

**Comment by NAT0P0TAT0** [comment]
added some cylinders with a copy of the coin material and just set them to rotate constantly, then disabled the previous wheels
